name: dart_autogui
description: A desktop automation library built on top of python's pyautogui module
version: 0.0.1
homepage: https://www.github.com/pacifio/dart-autogui

environment:
  sdk: ">=2.12.0 <3.0.0"
